### ISSUE TITLE
Allow passwords of any length

### ISSUE THREAD

**Issue by henrahmagix** [wildfoundry/dataplicity#2] opened 2014-07-12 12:24 UTC
Currently the limit is 20. Why?

![image](https://cloud.githubusercontent.com/assets/1429026/3561394/3a313876-09bf-11e4-9ed2-c3e614d74f75.png)

**Comment by meshy** [comment] 2016-02-08 11:42
Hey @henrahmagix! I can't reproduce this, so I think that this must have been fixed at some point. Can you please double-check for me before I close this issue?

Hope all's well! `:)`

**Comment by henrahmagix** [comment] 2016-02-08 11:50
I can't find this form, so I tried entering my email and clicking "Start", then a password box popped up: I put in a 30 character password, clicked "Set password", then the popup hid away and nothing happened. I clicked "Start" again and the password box popped up again with my password already filled in, like it never submitted. No console errors.

**Comment by henrahmagix** [comment] 2016-02-08 11:50
It never signed me up: I cannot sign in with the password I used.

**Comment by henrahmagix** [comment] 2016-02-08 11:51
However, the password field in the popup does show a green tick, so it must be an ok length.

**Comment by meshy** [comment] 2016-02-08 12:02
You should be able to find that form on https://dataplicity.com/settings/.

The problem registering is a little worrying. What's your web browser, and do you have any adblock plugins installed?

**Comment by henrahmagix** [comment] 2016-02-08 12:12
Chrome Latest, OS X, and I am using AdBlock.

There was a network request to `jsonrpc` that erred. It was the one that sent `params: {email: "blah", password: "blahalso"}`

**Comment by meshy** [comment] 2016-02-08 12:21
Ok, thanks, we're looking into this for you now.

**Comment by meshy** [comment] 2016-02-08 13:39
Ok, this time we're confident it's doing what it should. Are you happy to give it another go?

**Comment by henrahmagix** [comment] 2016-02-08 14:11
Yup, it works! However, there's no indication that it's "working on it" after submitting a password and the popup box hides away. I just waited a moment (~3 seconds) and the page changed to show the next step. Would be nice to have a loading thingy, either on the password box or over the whole page after the password box hides away.

**Comment by henrahmagix** [comment] 2016-02-08 14:12
So this can be closed =)

**Comment by meshy** [comment] 2016-02-08 14:22
Thanks again for the report and testing; glad it works. We'll be considering loading states properly for the upcoming UX work, so keep your eyes peeled.

**Closed** 2016-02-08 14:25 UTC

**Comment by henrahmagix** [comment] 2016-02-08 14:34
:+1:
